// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: events.sql

package repository

import (
	"context"
	"encoding/json"
	"time"
)

const getEvents = `-- name: GetEvents :many
SELECT id, aggregate_id, event_type, event_data, timestamp FROM events
WHERE aggregate_id = $1
ORDER BY timestamp ASC
`

func (q *Queries) GetEvents(ctx context.Context, aggregateID string) ([]Event, error) {
	rows, err := q.query(ctx, q.getEventsStmt, getEvents, aggregateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.EventType,
			&i.EventData,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveEvent = `-- name: SaveEvent :exec
INSERT INTO events (aggregate_id, event_type, event_data, timestamp)
VALUES ($1, $2, $3, $4)
`

type SaveEventParams struct {
	AggregateID string          `json:"aggregate_id"`
	EventType   string          `json:"event_type"`
	EventData   json.RawMessage `json:"event_data"`
	Timestamp   time.Time       `json:"timestamp"`
}

func (q *Queries) SaveEvent(ctx context.Context, arg SaveEventParams) error {
	_, err := q.exec(ctx, q.saveEventStmt, saveEvent,
		arg.AggregateID,
		arg.EventType,
		arg.EventData,
		arg.Timestamp,
	)
	return err
}
