// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"encoding/json"
	"time"
)

type Event struct {
	ID          int32           `json:"id"`
	AggregateID string          `json:"aggregate_id"`
	EventType   string          `json:"event_type"`
	EventData   json.RawMessage `json:"event_data"`
	Timestamp   time.Time       `json:"timestamp"`
}
