// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"
)

type Querier interface {
	GetEvents(ctx context.Context, aggregateID string) ([]Event, error)
	SaveEvent(ctx context.Context, arg SaveEventParams) error
}

var _ Querier = (*Queries)(nil)
